<?xml version="1.0" encoding="utf-8"?><Database Name="MyDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WKSBAN24KAN0008\SQLEXPRESS;Initial Catalog=MyDB;Integrated Security=True" SettingsObjectName="LINKDEMO.Properties.Settings" SettingsPropertyName="MyDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="employee_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="manager_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>